cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>/', views.full_remove, name='full_remove'),
]

studentboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('messageboard.urls')),
    path('', include('todo.urls')),
    path('', include('pages.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('vouchers/', include('vouchers.urls', namespace='vouchers')),
    path('wishlist/', include('wishlist.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wishlist/urls.py
from django.urls import path
from . import views

app_name = "wishlist"

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('', views.wishlist_detail, name='wishlist_detail'),
    path('delete_from_list/<uuid:product_id>/', views.delete_from_list, name='delete_from_list'),
]

wishlist/models.py
from django.db import models
from shop.models import Product

class Wishlist(models.Model):
    wishlist_id = models.CharField(max_length=250, blank=True)
    date_added = models.DateField(auto_now_add=True)

    class Meta:
        db_table = 'Wishlist'
        ordering = ['date_added']

    def __str__(self):
        return self.wishlist_id

class WishlistItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    wishlist = models.ForeignKey(Wishlist, on_delete=models.CASCADE)

    class Meta:
        db_table = 'WishlistItem'


    def __str__(self):
        return self.product

wishlist/views.py
from django.shortcuts import render, redirect, get_object_or_404
from shop.models import Product
from .models import Wishlist, WishlistItem
from django.db import models
from django.core.exceptions import ObjectDoesNotExist
from django.conf import settings
from django.contrib.auth.decorators import login_required

def _wishlist_id(request):
    wishlist = request.session.session_key
    if not wishlist:
        wishlist = request.session.create()
    return wishlist


@login_required
def add_to_wishlist(request, product_id):
    product = Product.objects.get(id=product_id)
    try:
        wishlist = Wishlist.objects.get(wishlist_id=_wishlist_id(request))
    except Wishlist.DoesNotExist:
        wishlist = Wishlist.objects.create(
            wishlist_id= _wishlist_id(request)
        )
        wishlist.save()
    try:
        wishlist_item = WishlistItem.objects.get(product=product, wishlist=wishlist)
        wishlist_item.save()
    except WishlistItem.DoesNotExist:
        wishlist_item = WishlistItem.objects.create(
                    product = product,
                    wishlist = wishlist
            )
        wishlist_item.save()
    return redirect('wishlist:wishlist_detail')

@login_required
def wishlist_detail(request, wishlist_items=None):
   try:
      wishlist = Wishlist.objects.get(wishlist_id=_wishlist_id(request))
      wishlist_items = WishlistItem.objects.filter(wishlist=wishlist)
   except ObjectDoesNotExist:
      pass
   return render(request, 'wishlist.html', {'wishlist_items': wishlist_items} )


@login_required
def delete_from_list(request, product_id):
    wishlist = Wishlist.objects.get(wishlist_id=_wishlist_id(request))
    product = get_object_or_404(Product, id=product_id)
    wishlist_item = WishlistItem.objects.get(product=product, wishlist=wishlist)
    wishlist_item.delete()
    return redirect('wishlist:wishlist_detail')

wishlist/templates/wishlist.html
{% load static %}



{% block content %}
{% include 'header.html' %}

{% include 'shopBase.html' %}

<head>
    <link rel="stylesheet" href="{% static 'css/products.css' %}">
</head>
<div class=" row pl-4">
    <div class="col-6">
        <h3 class="pl-3"></h3>
        <a href="{% url 'products' %}" class="back_icon"><i class="far fa-arrow-alt-circle-left"></i></a>
    </div>
    <div class="col-6 ">
        <form class="col-5 md-form active-cyan active-cyan-2 mr-5 float-right " action="{% url 'product_search' %}"
            method="get">
            <input name="p" class="form-control" type="text" placeholder="Search products..." aria-label="Search">
        </form>
    </div>
</div>

{% if not wishlist_items %}
<div>
    <div class="text-center">
        <br>
        <h1 class="text-center my_title">
            Your wishlist is empty <i class="far fa-frown"></i>
        </h1>
        <br>
        <p class="text-center">
            Please click <a href="{% url 'products' %}">here</a> to continue shopping.
        </p>
    </div>
</div>
{% else %}




<div class="row mx-auto pl-4">

    {% for item in wishlist_items %}
    <div class=" col-9 col-lg-3 col-sm-12 col-md-4 py-4">
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front">
                    <img class="mt-2" src="{{item.product.image_thumbnail.url}}" alt="{{item.product.name}}"
                        style="width:auto;height:auto;">
                    <h5>{{item.product.name}}</h5>
                    <p>€{{item.product.price}}</p>
                </div>
                <div class="flip-card-back text-center pt-4">

                    <img class="mb-2" src="{{item.product.image_thumbnail.url}}" alt="{{item.product.name}}"
                        style="width:70px;height:70px;">
                    <h5>{{item.product.name}} </h5>
                    <p>€{{item.product.price}}</p>
                    <p>{{item.product.description}}</p>
                    {% if item.product.available %}
                    <p class="text-success font-weight-bold">{{item.product.stock}} in stock <a
                            href="{% url 'wishlist:delete_from_list' item.product.id %}" class="custom_icon"><i
                                class="fas fa-minus-circle ml-4"></i> Remove</a></p>
                    <a class="btn btn-secondary" href="{% url 'cart:add_cart' item.product.id %}">Add to
                        cart</a>

                    {% else %}
                    <p>Currently out of stock</p>
                    {% endif %}





                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endif %}
{% include 'footer.html' %}
{%endblock%}