cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_cart, name='add_cart'),
    path('', views.cart_detail, name='cart_detail'),
    path('remove/<uuid:product_id>/', views.cart_remove, name='cart_remove'),
    path('full_remove/<uuid:product_id>/', views.full_remove, name='full_remove'),
]

order/urls.py
  
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('thanks/<int:order_id>/', views.thanks, name='thanks'),
    path('history/', views.orderHistory, name='order_history'),
    path('<int:order_id>/', views.viewOrder, name='order_detail'),
]

shop/urls.py
from django.urls import path
from . import views 
from .views import ProductSearchResultsView



urlpatterns = [
    path('', views.product_list, name='products'),
    path('<uuid:category_id>/', views.product_list, name='product_list_by_category'),
    path('product/search/', ProductSearchResultsView.as_view(), name='product_search'),


]

studentboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('messageboard.urls')),
    path('', include('todo.urls')),
    path('', include('pages.urls')),
    path('shop/', include('shop.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('vouchers/', include('vouchers.urls', namespace='vouchers')),
    path('wishlist/', include('wishlist.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

wishlist/urls.py
from django.urls import path
from . import views

app_name = "wishlist"

urlpatterns = [
    path('add/<uuid:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('', views.wishlist_detail, name='wishlist_detail'),
    path('delete_from_list/<uuid:product_id>/', views.delete_from_list, name='delete_from_list'),
]

shop/models.py
from django.db import models
import uuid
from django.urls import reverse
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill

class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField(max_length=250, blank=True)
    image = models.ImageField(upload_to='category', blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    stock = models.IntegerField()
    color = models.CharField(max_length=20, blank=True)
    image_thumbnail = ImageSpecField(source='image', 
                                        processors=[ResizeToFill(280, 230)], 
                                        format='JPEG', 
                                        options={'quality': 300})

    def __str__(self):
        return self.name


class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=100, unique=True)
    descripton = models.TextField(max_length=250, blank=True)
    products = models.ManyToManyField('Product')

    def get_products(self):
        return Product.objects.filter(category=self)
    
    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('product_list_by_category',args=[self.id])
    
    

shop/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Category, Product
from django.db.models import Count, Q
from django.views.generic import ListView



def product_list(request, category_id=None):
    category = None
    products = Product.objects.all()
    ccat = Category.objects.annotate(num_products=Count('products'))
    
    if(category_id):
        category = get_object_or_404(Category, id=category_id)
        products = products.filter(category=category)
    
    return render(request, 'products.html',
                    {'products': products,
                    'countcat':ccat})

class ProductSearchResultsView(ListView):
    model = Product
    context_object_name = 'all_products_list'
    template_name = 'product_search.html'

    def get_queryset(self):
        query = self.request.GET.get('p')
        return Product.objects.filter(Q(name__icontains=query) | Q(description__icontains=query))

shop/templates/footer.html
<div class="text-center">
    <footer>
        <a class="nav-link" href="{% url 'products' %}">Browse all products</a>
        <a href="{% url 'home' %}">Back to StudentBoard</a>
        <p class="text-center">&copy; TUD Merch. All Rights Reserved.</p>
    </footer>

</div>

shop/templates/header.html
<div class=" jumbotron text-center">
    <h1 class="display-5">Welcome to the</h1>
    <h1 class="display-4">TUD-Tallaght Merch Store!</h1>
    <p>Introducing our new 2020 TUD-Tallaght merchandise store! </p>
    <p>Now with TUD branded products!</p>

</div>

shop/templates/product_search.html
{% load static %}



{% block content %}
{% include 'header.html' %}

{% include 'shopBase.html' %}

<head>
    <link rel="stylesheet" href="{% static 'css/products.css' %}">
</head>
<div class=" row pl-4">
    <div class="col-6">
        <h3 class="pl-3">Search Results:</h3>
        <a href="{% url 'products' %}" class="back_icon"><i class="far fa-arrow-alt-circle-left"></i></a>
    </div>
    <div class="col-6 ">
        <form class="col-5 md-form active-cyan active-cyan-2 mr-5 float-right " action="{% url 'product_search' %}"
            method="get">
            <input name="p" class="form-control" type="text" placeholder="Search products..." aria-label="Search">
        </form>
    </div>
</div>
<div class="row mx-auto pl-4 ">
    {% for product in all_products_list %}
    <div class=" col-9 col-lg-3 col-sm-12 col-md-4 py-4">
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front">
                    <img class="mt-2" src="{{product.image_thumbnail.url}}" alt="{{product.name}}"
                        style="width:auto;height:auto;">
                    <h5>{{product.name}}</h5>
                    <p>€{{product.price}}</p>
                </div>
                <div class="flip-card-back text-center pt-4">
                    <div class="">
                        <img class="mb-2" src="{{product.image_thumbnail.url}}" alt="{{product.name}}"
                            style="width:70px;height:70px;">
                        <h5>{{product.name}} </h5>
                        <p>€{{product.price}}</p>
                        <p>{{product.description}}</p>
                        {% if product.available %}
                        <p class="text-success font-weight-bold">{{product.stock}} in stock</p>
                        {% else %}
                        <p>Currently out of stock</p>
                        {% endif %}
                        <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% include 'footer.html' %}
{%endblock%}

shop/templates/products.html
{% load static %}
{% block content %}
{% include 'header.html' %}
{% include 'shopBase.html' %}

<head>
    <link rel="stylesheet" href="{% static 'css/products.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

</head>
<form class="col-2 md-form active-cyan active-cyan-2 ml-4 " action="{% url 'product_search' %}" method="get">
    <input name="p" class="form-control" type="text" placeholder="Search products..." aria-label="Search">
</form>
<script>
$(window).on('load',function(){
  if (!sessionStorage.getItem('shown-modal')){
    $("#myModal").modal('show');
    sessionStorage.setItem('shown-modal', 'true');
  }
});
</script>
</head>

<body>
    <div id="myModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3 class="modal-title"><i class="fas fa-gift"></i> A Christmas Treat Just For You! <i
                            class="fas fa-gift"></i></h3>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <h4>To thank you for being a valued customer, we are giving you a 20% coupon for our shop!</h4>
                    <p>Simply enter the code <b><u>CHRISTMAS20</u></b> at the checkout!</p>
                </div>
            </div>
        </div>
    </div>
    <div class="row mx-auto pl-4">

        {% for product in products %}
        <div class=" col-9 col-lg-3 col-sm-12 col-md-4 py-4">
            <div class="flip-card">
                <div class="flip-card-inner">
                    <div class="flip-card-front">
                        <img class="mt-2" src="{{product.image_thumbnail.url}}" alt="{{product.name}}"
                            style="width:auto;height:auto;">
                        <h5>{{product.name}}</h5>
                        <p>€{{product.price}}</p>
                    </div>
                    <div class="flip-card-back text-center pt-4">
                        <div class="">
                            <img class="mb-2" src="{{product.image_thumbnail.url}}" alt="{{product.name}}"
                                style="width:70px;height:70px;">
                            <h5>{{product.name}} </h5>
                            <p>€{{product.price}}</p>
                            <p>{{product.description}}</p>
                            {% if product.available %}
                            <p class="text-success font-weight-bold">{{product.stock}} in stock</p>

                            {% else %}
                            <p>Currently out of stock</p>
                            {% endif %}
                            <a class="btn btn-secondary" href="{% url 'cart:add_cart' product.id %}">Add to cart</a>
                            <a class=" text-white btn far fa-bookmark"
                                href="{% url 'wishlist:add_to_wishlist' product.id %}"> Add to wishlist</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>

    {% endblock content %}
    {% include 'footer.html' %}

shop/templates/shopBase.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TUD-Merch</title>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Cabin:wght@700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>

    <title>{% block title %}{% endblock %}</title>
</head>

<body>
    <div class='container-fluid  navbar-fixed-top'>
        {% include 'top_nav.html' %}
    </div>
    <nav class="nav nav-pills nav-justified h5 p-4">
        {% for c in countcat %}
        {% if c.name != "Men's" %}
        {% if c.name != "Ladies" %}
        <a class="nav-item nav-link" href="{{ c.get_absolute_url }}">{{c.name}}</a>
        {% endif %}
        {% endif %}
        {% endfor %}
        {% for c in countcat %}
        {% if c.name == "Men's" %}
        <a class="nav-item nav-link disabled" href="{{ c.get_absolute_url }}">{{c.name}}</a>
        {% endif %}
        {% if c.name == "Ladies" %}
        <a class="nav-item nav-link disabled" href="{{ c.get_absolute_url }}">{{c.name}}</a>
        {% endif %}
        {% endfor %}

    </nav>

</body>

</html>

{%block content%}
{%endblock%}

shop/templates/top_nav.html
<div class="my_custom_menu">
	<ul>
		{% if user.is_authenticated %}
		<li>
			Welcome, <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-haspopup="true"
				aria-expanded="false">{{ user.username }}
				<i class="fas fa-user-circle"></i></a>
			<div class="dropdown-menu dropdown-menu-right">
				<a class="dropdown-item" href="{% url 'order:order_history' %}">Order History</a>
				<a class="dropdown-item" href="{% url 'wishlist:wishlist_detail' %}">Wish List</a>
			</div>

		</li>
		<li>
			<a href="{% url 'logout' %}">Sign Out <i class="fas fa-sign-out-alt"></i></a>
		</li>
		{% else %}
		<li>
			<a href="{% url 'signup' %}">Sign Up <i class="fas fa-user-plus"></i></a>
		</li>
		<li>
			<a href="{% url 'login' %}">Sign In <i class="fas fa-sign-in-alt"></i></a>
		</li>
		{% endif %}
		<li>
			<a href="{% url 'cart:cart_detail' %}"><i class="fas fa-shopping-cart"></i>({{item_count}})</a>
		</li>
	</ul>

</div>